### ISSUE TITLE
synchronize utils_ppser.f90 with version in cosmo

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/serialbox#13]
The file utils_ppser.f90 is out of sync with the version we have in cosmo. We need to sync it.

**Comment by clementval** [comment]
@cosunae @andyspiros Sync or separate stuff that are cosmo related that what should really be in `utils_ppser.f90`.

**Comment by clementval** [comment]
Related with #14

**Comment by havogt** [comment]
Fixed in Serialbox2
