### ISSUE TITLE
pp_ser: split generic VS. cosmo related code generation part

### ISSUE THREAD

**Issue by clementval** [MeteoSwiss-APN/serialbox#14]
Currently, some code generated by `pp_ser.py` is deeply related to variable or other stuffs in cosmo.

We should separate these parts. 

There is also specific part in Fortran modules such as tracer serialization (in the COSMO version of the module and pp_ser). 

When this is done, we should also think if it make sense to separate the read perturbation feature of serialbox and put it in a "cosmo" module.

**Comment by clementval** [comment]
For example, this part `register` directive should be part of a config file

https://github.com/MeteoSwiss-APN/serialbox/blob/master/python/pp_ser.py#L130

**Comment by clementval** [comment]
Related with #13

**Comment by havogt** [comment]
Fixed in Serialbox2
