### ISSUE TITLE
Having full Fortran example 

### ISSUE THREAD

**Issue by clementval** [MeteoSwiss-APN/serialbox#15]
Using serialbox with `pp_ser`, I noticed that it is quite hard to have a functional code directly. We really need to have some code samples to help people using serialbox

**Comment by cosunae** [comment]
+1

**Comment by clementval** [comment]
There is no a full write/read/read-perturb example here 
https://github.com/MeteoSwiss-APN/serialbox/tree/master/examples/perturbation
