### ISSUE TITLE
Adding ability to write and read logical array in the Fortran interface. 

### ISSUE THREAD

**Issue by clementval** [MeteoSwiss-APN/serialbox#25]
In the old dump, we had this trick to convert an array ... (probably can be an int instead of a real but it's old code anyway)

``` Fortran
DO j=1,je
  DO i=1,ie
    ! logical
    IF (llandmask_real(i,j) > 0.5_wp) THEN
      llandmask(i,j) = .TRUE.
    ELSE
      llandmask(i,j) = .FALSE.
    ENDIF
  ENDDO
ENDDO
```

Currently, serialboy doesn't allow to serialize logical array. It would be nice to have this function at least from fortran and to hide the conversion inside it.

**Comment by havogt** [comment]
@clementval If I understand correctly this feature is implemented?

**Comment by clementval** [comment]
I think so. But never tested myself

**Comment by havogt** [comment]
Probably fixed...
