### ISSUE TITLE
package libraries together

### ISSUE THREAD

**Issue by clementval** [MeteoSwiss-APN/serialbox#26]
Currently, there are at least 6 libraries part of the link step if you use serialbox from fortran code. 

I guess, there are 5 if you use from C code and "only" 4 if you use it directly from C++. 

Wouldn't it be nicer to package those libraries together and have a single one to be used from program using serialbox (or maybe three different packaging C++/C/Fortran):
- C++ serialbox lib contains the 4 needed libs
- C serialbox lib contains the 5 needed libs
- Fortran serialbox lib contains the 6 needed libs

Example of the currently needed libraries for a Fortran/CMake integration

``` cmake
target_link_libraries(standalone FortranSer.a)
target_link_libraries(standalone SerialBoxWrapper.a)
target_link_libraries(standalone SerialBox.a)
target_link_libraries(standalone Utils.a)
target_link_libraries(standalone sha256.a)
target_link_libraries(standalone json.a)
target_link_libraries(standalone stdc++.a)
```

It can be quite easily done with something like that 

``` bash
ar crsT libserialboxfortran.a FortranSer.a SerialBoxWrapper.a SerialBox.a Utils.a sha256.a json.a ...
```

**Comment by cosunae** [comment]
I think is good idea to bundle at least some of them, yes.
Does it make sense to have a lib with C++, another with the C wrappers and a last one with the fortran, i.e. 3 libraries?
That would actually mean packing Utils, sha256 and json inside SerialBox?
perhaps we could also make a more clear naming convention for library names. 
What about stdc++? this is not serialbox but a system library, should we link the FortranSer with it?

**Comment by havogt** [comment]
Fixed in Serialbox2
