### ISSUE TITLE
support for fortran and C++ compilers

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/serialbox#29]
Even though seriablox is being installed with two compilers (cray, gnu) At the moment we have problems compiling and running seriabox (C++ and fortran with cray), so we have to compile at least the C++ with gnu. 
Therefore we need to either debug the issue with cray compiler or allow the build scripts to compile C++ with gnu and fortran with cray.

At the moment the build with cray is not supported and falls back into gnu

**Comment by havogt** [comment]
This is partly fixed in Serialbox2 (all c++ is compiled with gnu, fortran is compiled with cray, pgi, gnu)
