### ISSUE TITLE
Potential linker error in SerializerUnittest because GTest depending on PThreads

### ISSUE THREAD

**Issue by thfabian** [MeteoSwiss-APN/serialbox#54]
The current way of linking SerializerUnittest may result in a linker error as GTest _depends_ on pthreads. Currently, pthreads is just added to the  `CMAKE_EXE_LINKER_FLAGS` and it may very well happen that `-lpthread` appears ahead of `-lgmock-gtest` and thus result in a linker error as `-lpthread` has to appear _after_ `-lgmock-gtes` to correctly resolve the dependencies.

A fix would be to add the follwowing to `serialbox/libs/gmock-gtest/CMakeLists.txt` to explicitly set this dependency.

```
target_link_libraries(gmock-gtest ${CMAKE_THREAD_LIBS_INIT})
```

**Comment by cosunae** [comment]
indeed, thanks Fabian, we have this in other projects. 
Are you missing 

`````` C++
find_package(Threads)```

if you have it in a working copy, you could create a PR with this?
``````
